<a href="https://colab.research.google.com/github/vishnucode17/Upgrade-Assignments/blob/main/Let's_Upgrade_Assignment_3_Day_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Question 1

Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [ ]:
import numpy as np # importing numpy library as np 
arr=np.arange(2,50,3) # arange() function is used to get consective numbers and if 3rd parameter denotes the stepsize
print(arr) # printing arr

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [ ]:
lst=[] # intialising an empty list
for x in range(5):
  a=[int(x) for x in input().split(',')] # taking input from user and storing them in list a
  lst.append(a) # appending the list a to list lst
np.array(lst) # converting list to numpy array

1,2,3
4,5,6
7,8,9
10,11,12
13,14,15


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

# Question 3

Write a code snippet to find the dimensions of a ndarray and its size.

In [ ]:
arr=np.array([[1,2,3],[3,4,5],[3,4,6]]) # creating a numpy array
print(arr.ndim) # printing the dimesions of an array
print(arr.shape) # printing the shape of an array
print(arr.size) # printing the size of an array

2
(3, 3)
9


# Question 4

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [ ]:
# converting a 1D array to 2D array can be acheived by reshaping the dimensions of the array by using reshape function in numpy library
arr=np.array([1,2,3,4]) # creating a numpy array of shape (4,)
print(arr.ndim) # checking the dimensions of array
arr=arr.reshape(2,2) # reshaping (4,) 1D array to (2,2) 2D array
print(arr.ndim) # checking the dimensions of the array
print(arr)

1
2
[[1 2]
 [3 4]]


In [ ]:
# another way using np.expand_dims without reshaping
arr=np.array([1,2,3,4]) # creating a numpy array of shape (4,)
new_arr = np.expand_dims(a, axis=0) # declaring new array named new_arr for expanding dimensions of array arr
print(new_arr) # printing the new_arr
print(new_arr.ndim) # printing the dimensions of the new_arr

[[13 14 15]]
2


# Question 5

Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [ ]:
arr1=np.array([[1,2],[3,4]]) # creating a square array and naming it as arr1
arr2=np.array([[7,8],[9,10]]) # craeting a square array and naming it as arr2
v_arr=np.vstack((arr1,arr2)) # using vstack for stacking two arrays vertically
print(v_arr) # printing vertically stacked array
h_arr=np.hstack((arr1,arr2)) # using hstack for stcaking two arrays horizontally
print(h_arr) # printing horixantally staked array

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]]
[[ 1  2  7  8]
 [ 3  4  9 10]]


# Question 6

How to get unique items and counts of unique items?

In [ ]:
arr=np.array([1,2,3,1,2,1,3,4,3,5,6,7,8]) # initialising a numpy array 
result_arr=np.unique(arr,return_counts=True) # using np.unique function returns the unique elements in the array and its count when return_counts is True
print(result_arr) #printing the resulting array

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([3, 2, 3, 1, 1, 1, 1, 1]))
